Don't bump upload activity on incomplete torrents
transmission/transmission pull request #1063
Opened 2019-11-25 02:57 UTC by kilobyte

Described in issue #995; retargetted version of #998.  With this, you have a way to spot dead torrents that are not going to ever complete, despite other people wanting to download them as well.

2022-01-23 11:07 UTC, kilobyte commented
Rebased and adapted for current master, please merge.

2022-01-23 15:55 UTC, ckerr commented
I don't think this is the right way to fix #995. `tr_stat.activityDate` is defined this way:

```c++
      /** The last time we uploaded or downloaded piece data on this torrent. */
      time_t activityDate;
```

This PR breaks that definition.

I'd be OK with adding a pair of fields that distinguish between up & down piece data alongside this, but we should keep `activityDate` as-is to avoid breaking existing RPC clients.

2022-01-23 15:56 UTC, ckerr requested changes
I don't think this is the right way to fix #995. `tr_stat.activityDate` is defined this way:

```c++
      /** The last time we uploaded or downloaded piece data on this torrent. */
      time_t activityDate;
```

This PR breaks that definition.

I'd be OK with adding a pair of fields that distinguish between up & down piece data alongside this, but we should keep `activityDate` as-is to avoid breaking existing RPC clients.

2022-01-23 16:00 UTC, kilobyte commented
So the display would switch to the new field?  (I see little reason to clutter the UI with both)

2022-01-24 00:09 UTC, pmarsden commented
The display should either remain as it is, or display both the split values (i.e. Upload and Download).
(In which case displaying the old [combined] value would not be necessary).

2022-08-26 01:11 UTC, ckerr commented
Closing due to lack of response.

I'd still be open to this kind of a feature if OP, or anyone else, wants to make a new PR

2022-08-26 01:11 UTC, closed without merging