Add MacStadum and SignPath sponsor links to readme
transmission/transmission pull request #2105
Opened 2021-11-05 21:38 UTC by mikedld

MacStadium asks to "put the MacStadium Open Source Developer logo on your landing page (either your GitHub page or website)". We're using Mac Mini M1 they provide for CI builds.

SignPath asks that "a code signing policy must be specified on the project’s home page". We're using the certificate provided by SignPath Foundation and the service provided by SignPath.io to sign release builds on Windows. The policy mention is already in place and the logo is not strictly necessary, but I value their support in this area and want to link back more prominently.

2021-11-05 21:41 UTC, ckerr requested changes
Is it required to go at the top like that? I'm fine with adding the links but this seems intrusive.

Maybe there could be a section at the bottom for links like this with one-liner explanations of how the project uses them?

2021-11-05 21:51 UTC, mikedld commented
Just the way I think I saw some other projects do this for this kind of links. Might be that I'm not remembering it right.

2021-11-05 22:26 UTC, mikedld commented
How does is look now @ckerr?

2021-11-06 06:16 UTC, ckerr approved these changes
LGTM. Thanks!

2021-11-06 06:16 UTC, merged