New images for 'Message Log'
transmission/transmission pull request #2779
Opened 2022-03-17 03:54 UTC by GScottElshaw

With #2764 landing, some additional colour to help differentiate the different log types.

2022-03-24 05:55 UTC, ckerr commented
I don't really know good macOS UI so I'd rather defer to another reviewer, but this PR's been green for a week, so:

unless someone requests changes / is against this PR, I'm going to merge it tomorrow :smiley_cat: @livings124 @mikedld

2022-03-24 14:09 UTC, GScottElshaw commented
> I don't really know good macOS UI so I'd rather defer to another reviewer, but this PR's been green for a week, so:
> 
> unless someone requests changes / is against this PR, I'm going to merge it tomorrow 😺 

@ckerr Can Mr @DevilDimon possibly have a look?

2022-03-25 01:16 UTC, DevilDimon commented
The code is in macosx/MessageWindowController.mm, you'll need to create the right NSImages within `tableView:objectValueForTableColumn:` method. You might take a look how other images are created there for inspiration

2022-03-25 01:20 UTC, GScottElshaw commented
> You might take a look how other images are created there for inspiration

That's certainly how it worked for this PR 👍🏼  Thanks for the directions @DevilDimon.

2022-03-25 01:30 UTC, mikedld requested changes
1. Comparing existing and new icons, the former are circles with a slightly darker outline while the latter are octagons:

   <img width="576" alt="image" src="https://user-images.githubusercontent.com/298203/160035910-34989ac6-489d-4d89-bd2f-42536385f6b3.png">

   I think we need to take the new ones from the same place the old ones came from, which may well be macOS itself, looking at its general preferences dialog (although I see that the colors are in fact slightly different, at least in 12.2):

   <img width="350" alt="image" src="https://user-images.githubusercontent.com/298203/160036649-ba744924-95b5-4bb6-a7f4-52947f939377.png">

2. New icons aren't size-optimized which I think we did at some point because the size difference in dramatic, e.g. for 2x variants, existing ones are around 275 bytes while new ones are around 2300-2600 bytes.

3. New icons need to be added to macosx/CMakeLists.txt: https://github.com/transmission/transmission/blob/bd895b50526665c4c379a5670105cafe017d2ad1/macosx/CMakeLists.txt#L238

2022-03-25 01:59 UTC, GScottElshaw commented on .github/workflows/objective-c-xcode.yml
> +name: Xcode - Build and Analyze
> We're not using GitHub Actions, and I'm not really sure what this checks and why we need it.

I was using GitHub Desktop for this particular PR.

2022-03-25 02:10 UTC, GScottElshaw commented
> 1. Comparing existing and new icons, the former are circles with a slightly darker outline while the latter are octagons:
>    <img alt="image" width="576" src="https://user-images.githubusercontent.com/298203/160035910-34989ac6-489d-4d89-bd2f-42536385f6b3.png">
>    I think we need to take the new ones from the same place the old ones came from (if such a place exists), which may well be macOS itself, looking at its general preferences dialog (although I see that the colors are in fact slightly different, at least in 12.2):
>    <img alt="image" width="350" src="https://user-images.githubusercontent.com/298203/160036649-ba744924-95b5-4bb6-a7f4-52947f939377.png">
> 2. New icons aren't size-optimized which I think we did at some point because the size difference in dramatic, e.g. for 2x variants, existing ones are around 275 bytes while new ones are around 2300-2600 bytes.
> 3. New icons need to be added to macosx/CMakeLists.txt: https://github.com/transmission/transmission/blob/bd895b50526665c4c379a5670105cafe017d2ad1/macosx/CMakeLists.txt#L238

This is a stop-gap PR that includes my own graphic design limitations. Each of the new images are taken from the images that existed within the codebase with personal limitations in changes until i can figure a better way; but at the scale they are, without that level of magnification, they work fine.

I would love to be able to add MacOS native icon colours in a similar fashion to what was done [here](https://github.com/transmission/transmission/blob/main/macosx/Images/TransmissionDocument.icns), but that's another PR for another day.

2022-03-25 02:15 UTC, ckerr commented on .github/workflows/objective-c-xcode.yml
> +name: Xcode - Build and Analyze
Please remove this change since it's off-topic to this PR :slightly_smiling_face:

2022-03-25 02:25 UTC, ckerr requested changes
#2813 and #2814 should be folded into this PR. They feel like they're part of this PR rather than standalone changes.

2022-03-25 02:34 UTC, GScottElshaw commented on .github/workflows/objective-c-xcode.yml
> +name: Xcode - Build and Analyze
Done

2022-03-25 03:04 UTC, GScottElshaw commented
> #2813 and #2814 should be folded into this PR. They feel like they're part of this PR rather than standalone changes.

Sorry Charles, I don't know how to do that.

2022-03-25 18:41 UTC, mikedld commented
@GScottElshaw in my experience it should be quite easy to take existing dot image in one color and change it into another color by simply playing with various [color values](https://en.wikipedia.org/wiki/HSL_and_HSV) in your favorite image editor. You don't need to paint a single pixel yourself. You may even be able to [use ImageMagick](https://legacy.imagemagick.org/Usage/color_mods/) for that if you're more of a CLI guy.

2022-03-25 21:35 UTC, GScottElshaw commented
> @GScottElshaw in my experience it should be quite easy to take existing dot image in one color and change it into another color by simply playing with various [color values](https://en.wikipedia.org/wiki/HSL_and_HSV) in your favorite image editor. You don't need to paint a single pixel yourself. You may even be able to [use ImageMagick](https://legacy.imagemagick.org/Usage/color_mods/) for that if you're more of a CLI guy.

You'd think, right? I'll have another go, @mikedld, but image manipulation, obviously, isn't my forte.

2022-03-28 04:52 UTC, GScottElshaw commented
Are you happy for this to be pushed, @mikedld?

2022-03-29 23:42 UTC, GScottElshaw commented
Can someone please review? Lots and lots of PR's piling up, from others too - a good thing! @ckerr @mikedld @livings124

2022-03-31 02:27 UTC, GScottElshaw commented on macosx/MessageWindowController.mm
>              return [NSImage imageNamed:@"PurpleDotFlat"];
Thanks Mike, great catch!

2022-03-31 02:34 UTC, mikedld approved these changes

2022-03-31 17:11 UTC, GScottElshaw commented
@ckerr Pull the trigger please Charles.

2022-04-01 17:24 UTC, ckerr commented
@GScottElshaw is this still of a piece with #2813 and #2814 ?

2022-04-02 00:21 UTC, GScottElshaw commented
> @GScottElshaw is this still of a piece with #2813 and #2814 ?

@ckerr Unless i accidentally did the right thing, yes.

2022-04-02 01:48 UTC, GScottElshaw commented
Some weirdness in the values that have nothing to do with my proposed changes. Why "yoL-9H-kTt" and "2hu-LL-6A5"?

<font key="font" metaFont="menu"/>
                            <menu key="menu" title="OtherViews" id="16">
                                <items>
                                    <menuItem title="Error" state="on" image="RedDotFlat" id="17"/>
                                    <menuItem title="Warn" image="RedDotFlat" id="yoL-9H-kTt"/>
                                    <menuItem title="Info" image="GreenDotFlat" id="18"/>
                                    <menuItem title="Debug" image="BlueDotFlat" id="19"/>
                                    <menuItem title="Trace" image="PurpleDotFlat" id="2hu-LL-6A5"/>
                                </items>
                            </menu>

2022-04-02 05:57 UTC, ckerr approved these changes

2022-04-02 15:02 UTC, GScottElshaw commented
@ckerr Hi Charles, i'm sure you've seen TC isn't so happy with its Gentoo boxes right now. Do you think it's time to merge this, regardless?

2022-04-03 01:08 UTC, ckerr commented
CI failure is unrelated to PR

2022-04-03 01:08 UTC, merged

2022-04-03 01:14 UTC, GScottElshaw commented
Thank you Charles!