Update MessageWindowController.mm
transmission/transmission pull request #2813
Opened 2022-03-25 01:51 UTC by GScottElshaw

An adjunct for #2779 that places the correct colours within the log windows.

2022-03-25 02:24 UTC, ckerr requested changes
Since they're so closely related, I think it makes more sense for #2813 and #2814 to be folded into #2779 as a single PR, rather than as three pieces?

@GScottElshaw please close these two followups and add these changes into #2779. Thanks!

2022-03-25 02:35 UTC, GScottElshaw commented
> @GScottElshaw please close these two followups and add these changes into #2779. Thanks!

@ckerr I would Charles, but i don't know how to do that ¯\_(ツ)_/¯

2022-03-29 01:03 UTC, GScottElshaw commented
Oh Gentoo PPC, how could you?

2022-04-01 17:58 UTC, ckerr reviewed
It looks like this is done in #2779 in https://github.com/transmission/transmission/pull/2779/commits/d4501f6faeff0044a1032c45cccd844b8106db8b ... so is #2813 still necessary, or should it be closed in favor of 2779?

2022-04-02 00:33 UTC, GScottElshaw commented
> It looks like this is done in #2779 in [d4501f6](https://github.com/transmission/transmission/commit/d4501f6faeff0044a1032c45cccd844b8106db8b) ... so is #2813 still necessary, or should it be closed in favor of 2779?

I did accidentally do the right thing didn't i.

2022-04-02 00:33 UTC, closed without merging