refactor: move tr_torrent callbacks to tr_session
transmission/transmission pull request #3003
Opened 2022-04-27 21:31 UTC by ckerr

A micro-optimization to reduce memory use: these five callbacks are always the same for every torrent, so move them into tr_session where client code can register the callback once instead of once per torrent. This removes five void pointers and five function pointers from each `tr_torrent` instance, which is not a huge savings but can add up when the number of torrents is large.

NB: the macOS client code needs to be updated to replace `tr_torrentSetCallback...(tor, foo)` with the new `tr_sessionSetCallbac...(session, foo)` replacements. @Coeur or @DevilDimon, are either of you two interested in doing that?

2022-04-29 07:41 UTC, Coeur commented
I will pass on this one, as I am busy these days.

By the way, the LGTM alert is a false positive (and a bug in their analyzer):
![Capture d’écran 2022-04-29 à 15 27 17](https://user-images.githubusercontent.com/839992/165902952-802e9a65-ad01-4ab7-ae81-30ab8576909e.png)

2022-04-29 11:46 UTC, Coeur requested changes
While I support this callbacks factoring,
Let's delay merging this until building from Xcode is resolved.
As it is, there would be an issue of the type:
>this breaks the macOS client code, which will need to be updated to replace the previous `tr_torrentSetCallback`...(tor, foo) with the new `tr_sessionSetCallback`...(session, foo) replacements.

Also, I recommend merging #2956 first, otherwise we are stacking regressions on building from Xcode.

2022-04-29 16:53 UTC, ckerr commented
9efef06 should fix the LGTM warning and resolves merge conflicts with main

2022-04-29 17:15 UTC, Coeur commented on libtransmission/session.h
> +            func(tor, data);
func(tional programing

2022-05-02 06:50 UTC, Coeur approved these changes

2022-05-14 15:00 UTC, merged