'beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo:' is deprecated:
transmission/transmission pull request #3031
Opened 2022-04-30 16:09 UTC by Coeur

2022-04-30 17:44 UTC, ckerr commented
ping @DevilDimon

2022-04-30 17:46 UTC, ckerr requested changes
Looks like the CI bots are a little healthier today (:heart: @mikedld) and the style bot found a place where this PR needs reformatting

```
[11:36:18 ](https://trtc.mikedld.com/buildConfiguration/Transmission_CodeStyle/207117?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&showLog=207117_333_333&logView=flowAware)  Creating 1f3bff43dd55cfe9_code_style_run ...
[11:36:18 ](https://trtc.mikedld.com/buildConfiguration/Transmission_CodeStyle/207117?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&showLog=207117_334_334&logView=flowAware)  Creating 1f3bff43dd55cfe9_code_style_run ... done
[11:36:19 ](https://trtc.mikedld.com/buildConfiguration/Transmission_CodeStyle/207117?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&showLog=207117_335_335&logView=flowAware)  checking code format
[11:36:20 ](https://trtc.mikedld.com/buildConfiguration/Transmission_CodeStyle/207117?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&showLog=207117_336_336&logView=flowAware)  ./macosx/FileRenameSheetController.mm:57:58: error: code should be clang-formatted [-Wclang-format-violations]
11:36:20   + (void)presentSheetForRenamer:(FileRenameSheetController *)renamer modalForWindow:(NSWindow *)window completionHandler:(void (^)(BOOL))completionHandler
[11:36:20 ](https://trtc.mikedld.com/buildConfiguration/Transmission_CodeStyle/207117?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&showLog=207117_337_337&logView=flowAware)                                                           ^
11:36:20   ./macosx/FileRenameSheetController.mm:57:68: error: code should be clang-formatted [-Wclang-format-violations]
11:36:20   + (void)presentSheetForRenamer:(FileRenameSheetController *)renamer modalForWindow:(NSWindow *)window completionHandler:(void (^)(BOOL))completionHandler
[11:36:20 ](https://trtc.mikedld.com/buildConfiguration/Transmission_CodeStyle/207117?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&showLog=207117_338_338&logView=flowAware)                                                                     ^
11:36:20   ./macosx/FileRenameSheetController.mm:57:93: error: code should be clang-formatted [-Wclang-format-violations]
11:36:20   + (void)presentSheetForRenamer:(FileRenameSheetController *)renamer modalForWindow:(NSWindow *)window completionHandler:(void (^)(BOOL))completionHandler
11:36:20                                                                                               ^
[11:36:20 ](https://trtc.mikedld.com/buildConfiguration/Transmission_CodeStyle/207117?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&showLog=207117_339_339&logView=flowAware)  ./macosx/FileRenameSheetController.mm:57:102: error: code should be clang-formatted [-Wclang-format-violations]
11:36:20   + (void)presentSheetForRenamer:(FileRenameSheetController *)renamer modalForWindow:(NSWindow *)window completionHandler:(void (^)(BOOL))completionHandler
[11:36:20 ](https://trtc.mikedld.com/buildConfiguration/Transmission_CodeStyle/207117?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&showLog=207117_340_340&logView=flowAware)                                                                                                       ^
[11:36:23 ](https://trtc.mikedld.com/buildConfiguration/Transmission_CodeStyle/207117?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&showLog=207117_348_348&logView=flowAware)  C/C++ code needs formatting
```

2022-04-30 17:47 UTC, Coeur commented
@ckerr you're a few seconds too late. :)
Already fixed

2022-05-14 07:53 UTC, ckerr approved these changes

2022-05-14 13:20 UTC, merged