docs: draft 4.0.0-beta.1 news
transmission/transmission pull request #3272
Opened 2022-06-12 20:31 UTC by ckerr

This is going to take a bit of work.

NOTE: This is all being done manually. If you're a contributor and I missed you I _guarantee_ you it's due to (my) human error. Please feel free to contribute to this draft.

2022-06-19 11:58 UTC, Coeur commented on news/news-4.0.0-beta-1.md
> +  - Support pasting multimple magnet links ([#3087](https://github.com/transmission/transmission/pull/3087), [#3086](https://github.com/transmission/transmission/pull/3086))
multimple > multiple

2022-06-22 08:05 UTC, tearfur requested changes
Very excited about this release. Just want to help out a tiny bit as a user.

2022-06-22 08:05 UTC, tearfur commented on news/news-4.0.0-beta-1.md
> +- The unit tests have been ported to [Google Test](http://bittorrent.org/beps/bep_0052.html). Many new tests, including fuzz testing, have been added. CI has been improved to run sanitizer builds of
Wrong link for Google Test?

2022-06-22 08:05 UTC, tearfur commented on news/news-4.0.0-beta-1.md
> +- Transmission 4.0.0 now supports .torrent files that were created with the [BitTorrent v2 spec](http://bittorrent.org/beps/bep_0052.html). 4.0.0 users will be able to download and seed torrents crea
```suggestion
- Transmission 4.0.0 now supports .torrent files that were created with the [BitTorrent v2 spec](http://bittorrent.org/beps/bep_0052.html). 4.0.0 users will be able to download and seed torrents created by both BitTorrent v1 and v2. Support for _creating_ v2 torrents is slated for the next major release of Transmission.
```

2022-06-22 17:23 UTC, Coeur commented on news/news-4.0.0-beta-1.md
> +  - Support pasting multimple magnet links ([#3087](https://github.com/transmission/transmission/pull/3087), [#3086](https://github.com/transmission/transmission/pull/3086))
```suggestion
  - Support pasting multiple magnet links ([#3087](https://github.com/transmission/transmission/pull/3087), [#3086](https://github.com/transmission/transmission/pull/3086))
```

2022-06-24 16:10 UTC, Coeur commented on news/news-4.0.0-beta-1.md
> +  - Support pasting multimple magnet links ([#3087](https://github.com/transmission/transmission/pull/3087), [#3086](https://github.com/transmission/transmission/pull/3086))
@ckerr not fixing this one?

2022-07-01 17:35 UTC, ckerr commented
> @ckerr what's the mystery deal for the one I commented above? musical_note smile

I don't understand the question?

2022-07-01 22:47 UTC, ckerr commented
Even though this is incomplete I think I'm just going to merge it anyway -- that way, other people can contribute PRs to add to it & improve it. There's still probably 2 weeks of coding left before we start freezing for release

2022-07-01 22:47 UTC, merged

2022-07-02 02:04 UTC, GaryElshaw commented
This is causing some breaks during CI.

```
CMake Error at cmake_install.cmake:50 (file):
  file INSTALL cannot find "/__w/transmission/transmission/src/NEWS.md": No
  such file or directory.
```