Raise minimum supported target to macOS 10.13 (High Sierra)
transmission/transmission pull request #3310
Opened 2022-06-16 16:43 UTC by fxcoudert

Looking at all comments in https://github.com/transmission/transmission/issues/3302 there seems to be a general agreement that 10.13 is a conservative value for `MACOSX_DEPLOYMENT_TARGET`. The corresponding Xcode is 10.

2022-06-16 17:06 UTC, Coeur commented
All the changes here (raising to Xcode 10 minimum, SYSTEM_HEADER_SEARCH_PATHS, ...) could be performed without touching at macOS minimum target.
So it feels there is no value to change from macOS 10.10 to 10.13.
But OK, fair, I don't have any device on such old versions and agree those are obsolete versions nowadays.

2022-06-16 17:29 UTC, fxcoudert commented
- Xcode 10 is the version matching macOS 10.13: it feels better to have a Xcode version that can actually run on the minimum macOS version
- `SYSTEM_HEADER_SEARCH_PATHS` was done automatically by Xcode when updating the Xcode setting
- I will check the codepaths mentionned

2022-06-16 18:59 UTC, nevack commented on macosx/Controller.mm
> +        indexes = [NSKeyedUnarchiver unarchivedObjectOfClass:NSIndexSet.class fromData:[pasteboard dataForType:TORRENT_TABLE_VIEW_DATA_TYPE]
You can merge declaration and assignment.
Also semicolons at arguments look better when are in the same column

```suggestion
        NSIndexSet* indexes = [NSKeyedUnarchiver unarchivedObjectOfClass:NSIndexSet.class
                                                                fromData:[pasteboard dataForType:TORRENT_TABLE_VIEW_DATA_TYPE]
                                                                   error:nil];
```

2022-06-16 18:59 UTC, nevack commented on macosx/GroupsPrefsController.mm
> +        indexes = [NSKeyedUnarchiver unarchivedObjectOfClass:NSIndexSet.class fromData:[pasteboard dataForType:GROUP_TABLE_VIEW_DATA_TYPE]
Same applies here

2022-06-16 19:10 UTC, fxcoudert commented
Style fixed, rebased after recent macOS commits.

2022-06-17 00:17 UTC, Coeur commented
> * Xcode 10 is the version matching macOS 10.13: it feels better to have a Xcode version that can actually run on the minimum macOS version

Just to clarify here: technically, Xcode 10 is already the minimum required version to compile the project. If you attempt to use the previous version, Xcode 9.4.1, then the file NSApplicationAdditions.mm won't build at all because they won't be able to find the symbol `NSAppearanceNameDarkAqua`. Hence why I said you could do all the changes from your first commit independently from raising the minimum macOS target.

2022-06-17 07:56 UTC, fxcoudert commented
By “Xcode 10 is the version matching macOS 10.13” I meant: “if you're stuck with macOS 10.13 for some reason, Xcode 10 is the highest version you can use”, i.e., if you have a fully updated macOS 10.13 box, you will have Xcode 10.

2022-06-17 13:54 UTC, Coeur commented
Ah yes. No other question from me. As a sensitive topic, I just recommend a second approval before merging.

2022-06-17 19:11 UTC, fxcoudert commented
Windows-only error when no non-mac files are changed 🤷

2022-06-17 21:35 UTC, nevack requested changes
@fxcoudert You need to update this line too
https://github.com/transmission/transmission/blob/main/CMakeLists.txt#L10

2022-06-17 21:46 UTC, nevack commented
@ckerr Charles, I think we are ready to merge it.
@fxcoudert Would you update Cask code to use 3.00 for 10.12 and older after 4.0 release?

2022-06-18 01:45 UTC, nevack commented
Oof, code-style fails :(

2022-06-18 01:59 UTC, ckerr commented
clang-format wants the changes listed here:
https://github.com/transmission/transmission/suites/6986543325/artifacts/273433896

2022-06-18 08:12 UTC, fxcoudert commented
Style fixed

2022-06-18 14:26 UTC, merged