tr_makeMetaInfo: new omitPII option (closes #3420)
transmission/transmission pull request #3452
Opened 2022-07-15 17:12 UTC by carandraug

* libtransmission/makemeta.cc (tr_makeMetaInfo): new argument omitPII.
  (tr_realMakeMetaInfo): skip addition of TR_KEY_created_by and
  TR_KEY_creation_date if omitting PII.
* libtransmission/makemeta.h (tr_metainfo_builder, tr_makeMetaInfo):
  new omitPII field and function argument.
* macosx/CreatorWindowController.mm: adjust call to tr_makeMetaInfo
  default to false (maintains previous behaviour)
* gtk/MakeDialog.cc: adjust call to tr_makeMetaInfo default to false
  (maintains previous behaviour)
* qt/MakeDialog.cc: adjust call to tr_makeMetaInfo default to false
  (maintains previous behaviour)
* tests/libtransmission/makemeta-test.cc: adjust calls to
  tr_makeMetaInfo defaulting to false.
* utils/create.cc: new '--omit-pii' option without one letter form.
* utils/transmission-create.1: document new '--omit-pii' option.

2022-07-17 18:07 UTC, Lanzaa approved these changes
Looks good to me.

2022-07-17 23:44 UTC, ckerr reviewed
I know I was the one who suggested the PII name, but on reflection I don't think it's accurate -- one's torrent client, for example, doesn't *personally* single out a particular person.

But the alternatives I can think of, e.g. "potentially identifying information" or "indirectly identifying information", are probably even *more* confusing.

What would you think about  `--anonymize`, `tr_builder.anonymize`, etc. instead of "omit pii"? Everything else would stay the same.

2022-07-19 15:22 UTC, ckerr commented
> I'm not familiar with your preferences for git history so I made the choice of fixing up the previous commit and force pushed it (in the interest of keeping history cleaner, nothing gained by having an extra commit that just changes the option name).

In the end, everything gets squash-merged into `main` to keep `main`'s history tidy, so the housekeeping in the PR branch is totally up to the submitter. But I do appreciate you taking it into consideration & keeping the PR clean too :-1:

2022-07-19 15:24 UTC, ckerr requested changes
Option is misspelled; it should be `anonymize` 

Other than that, the PR LGTM.

2022-07-19 17:32 UTC, carandraug commented
> Option is misspelled; it should be anonymize

Ups. It's fixed now.

2022-07-19 19:17 UTC, ckerr approved these changes

2022-07-19 21:48 UTC, ckerr commented
TeamCity CI failure is unrelated to PR; the openIndiana runner is offline

2022-07-19 21:48 UTC, merged