Transmission sans title (branding)
transmission/transmission pull request #3902
Opened 2022-10-07 22:18 UTC by GaryElshaw

This has been asked for a few times, most recently #3891, and this kinda goes against impulse to remove branding, but design-wise - i like it. This is a good start to the conversation anyway.

![SCR-20221008-fnv](https://user-images.githubusercontent.com/69029666/194670319-7edf5205-2111-4617-a447-c724f7d35045.png)

2022-10-08 07:51 UTC, Coeur commented
Thanks. At this point of the release cycle of Transmission 4, we have two options:
- either this UI change is only done behind a settings option (so by default, the app name is kept visible)
- or we target a Transmission 5 branch

But sorry I'm not in favour of imposing the removal of the app name just at the gates of a major version for which we want extra visibility.

2022-10-08 23:06 UTC, Pentaphon commented
I think so many Mac users will complain in the time between 4.0.0 and 5.0.0 that it's probably worth just letting this PR go through in time for 4.0.0 stable...

2022-10-08 23:28 UTC, Coeur commented
If really we're going this way for 4.0, then we'd also need to replace the various screenshots in the website repository. Has anyone some time to redo the four of them? @bexnoss ?


https://github.com/transmission/transmission.github.io/blob/master/assets/images/homepage/screenshot_apple.png
https://github.com/transmission/transmission.github.io/blob/master/assets/images/homepage/screenshot_mac_full_window.png
https://github.com/transmission/transmission.github.io/blob/master/assets/images/homepage/carousel_homepage/screenshot_apple.png
https://github.com/transmission/transmission.github.io/blob/master/assets/images/homepage/carousel_homepage/screenshot_apple_light.png

2022-10-09 01:24 UTC, sweetppro requested changes
setting fullSizeContentView="YES" causes the following window drawing issue:
<img width="355" alt="twin" src="https://user-images.githubusercontent.com/7323792/194733170-b6c6d1ff-7239-40d1-86d3-f3a9ef4e4930.png">

If this setting is unchecked from interface builder, I don't see any other issues

2022-10-09 01:31 UTC, sweetppro commented
if its not obvious, the screenshot is from the regular **_(not minimal view)_**

2022-10-09 01:35 UTC, sweetppro commented
@GaryElshaw also why was the window title removed, its enough to just check the `Hide Title text` checkbox

2022-10-09 03:49 UTC, GaryElshaw commented
> @GaryElshaw also why was the window title removed, its enough to just check the `Hide Title text` checkbox

There were spacing issues with the various icons. Although th title wasn't there, the space allocated for it remained. This is a proof of concept hack, it introduces other gui issues too... :-( #NeedHelp

2022-10-09 03:51 UTC, GaryElshaw commented
Closing in favour of #3919

2022-10-09 03:51 UTC, closed without merging