feat(qt): Add ETA to compact view
transmission/transmission pull request #3926
Opened 2022-10-10 01:44 UTC by pudymody

This adds ETA to the compact view.

Its mostly a copy and paste from the *progressString* function.

Should resolve #1392

2022-10-10 22:26 UTC, ckerr requested changes
Please apply code-style.diff from https://github.com/transmission/transmission/actions/runs/3222669022/ to make clang-format happy :smile_cat:

2022-10-10 22:29 UTC, ckerr requested changes

2022-10-10 22:29 UTC, ckerr commented on qt/TorrentDelegate.cc
> +        str += tr("    %1 left").arg(Formatter::get().timeToString(tor.getETA()));
Here and below, please don't mark layout whitespace as translatable; it's just throwing footguns at translators.

```suggestion
        str += QStringLiteral("   ");
        str += tr("%1 left").arg(Formatter::get().timeToString(tor.getETA()));
```

2022-10-27 13:58 UTC, ckerr approved these changes
Thanks!

2022-11-26 13:12 UTC, Coeur commented
If I'm not mistaken, this change adds the string `"%1 left"`, so I consider it too late for translations for the Transmission 4.0 release and I'm setting the Milestone 5.0 just like for #4169.

If I'm mistaken because that string is already existing, then feel free to change Milestone to 4.0.

2022-12-01 23:24 UTC, pudymody commented
Yes, its a new one.

Is almost the same as * - %1 left* that already exists, i could try to use them for the translation of this new one if wanted as the only difference is the space and dash. Text should have the same meaning and translation

2023-12-07 01:14 UTC, tearfur commented
@ckerr This PR looks like a low hanging fruit. Can we get it merged?

2023-12-16 16:32 UTC, merged

2024-12-12 22:32 UTC, ckerr commented
Notes: Added ETA to compact view.