fix: chrome needs vendor prefix(-webkit-) for mask
transmission/transmission pull request #4056
Opened 2022-10-31 13:48 UTC by trainto

![image](https://user-images.githubusercontent.com/6468924/199022361-26c35dc7-7c61-40b3-8718-6a8e894ac4e3.png)

Currently mime icons are not shown properly in Chrome. To fix this, vendor prefix(-webkit-) should be added to style.
(https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image#browser_compatibility)

And I'm not sure if I'm allowed to change stylelint config, but I added "property-no-vendor-prefix": null in it.

2022-10-31 21:16 UTC, ckerr commented
Hi @trainto, please remove `transmission-app.js` from this PR; see https://github.com/transmission/transmission/pull/4061 for rationale. Thank you!

2022-10-31 21:17 UTC, ckerr requested changes
Hi @trainto, please remove the `transmission-app.js` changes from this PR.

See https://github.com/transmission/transmission/pull/4061 for rationale. Thank you!

2022-11-01 00:39 UTC, trainto commented
Hi @ckerr, I removed the `transmission-app.js` changes. Thanks!

2022-11-01 00:44 UTC, GaryElshaw commented
Many thanks from an Ungoogled-Chromium user.

2022-11-03 20:51 UTC, ckerr approved these changes

2022-11-04 04:01 UTC, merged