Fix set_version "The left operand of '&' is a garbage value"
transmission/transmission pull request #4064
Opened 2022-11-01 07:33 UTC by Coeur

This fixes a warning in libutp.

2022-11-01 14:12 UTC, ckerr requested changes
This needs to be submitted to `transmission/libutp` and upstream to `bittorrent/libutp`.

I'm not sure what would happen if I hit the 'merge' button here in `transmission/transmission` but it's probably not good :slightly_smiling_face:

2022-11-01 16:21 UTC, ckerr commented
Ahhh gotcha. Thanks for the clarification :+1:

2022-11-01 16:22 UTC, ckerr approved these changes

2022-11-02 02:11 UTC, mikedld approved these changes

2022-11-02 05:39 UTC, merged