Fix building on macOS
transmission/transmission pull request #4155
Opened 2022-11-13 10:40 UTC by Coeur

This partially reverts #4147 until it builds again. There were multiple breaking changes, and it was maybe a bit premature to merge them in the absence of review and testing.

I'm not trying here to do the ideal fix of how it was intended to be by @mikedld: I'm simply doing a quick revert to a working state to unblock other macOS developers.

2022-11-13 10:51 UTC, mikedld requested changes
The build is working on CI. Just pass `CMAKE_OSX_DEPLOYMENT_TARGET` explicitly for the time being, or file a PR after figuring out why the provided default isn't being used.

2022-11-13 10:56 UTC, Coeur commented
@ckerr I'm withdrawing from the project until macOS build is broken. Please remove my "Collaborator" badge, thank you.

2022-11-13 10:58 UTC, GaryElshaw commented
> The build is working on CI.

Yes, but more of us are seeing the same error on macOS. https://github.com/transmission/transmission/issues/4151

2022-11-13 11:00 UTC, GaryElshaw commented
> @ckerr I'm withdrawing from the project while macOS build is broken. Please remove my "Collaborator" badge, thank you.

@Coeur I understand Antoine, but please reconsider.

2022-11-13 11:06 UTC, GaryElshaw commented
@mikedld No personal shade, but this change is alienating all of us who live in macOS. Is there any desire on your part to ask for some consensus?

2022-11-13 11:29 UTC, mikedld commented
I'm sorry but I'm not a fan of reverting changes that were in fact tested, especially if there's time for a proper fix. As noted before, the issue is with `CMAKE_OSX_DEPLOYMENT_TARGET`, so I'm closing this in favor of #4156.

Not sure why you're reacting the way you do if you're seemingly using the Xcode project (most of the time?) anyway. It's not a critical issue to fall on a sword for if there's a perfectly acceptable workaround.

2022-11-13 11:29 UTC, closed without merging

2022-11-13 11:44 UTC, GaryElshaw commented
It's okay, I don't think you're understanding, Mike. The changes may have worked on all of the testing, but don't work when passed to users trying to build. I think my, and maybe others, frustration is about understanding. It's okay to say you're not a fan of reverting changes, but if those changes are a regression to building, where do we start that conversation?

2022-11-13 11:45 UTC, GaryElshaw commented
Also, closing an issue is a brutal way to kill conversation.

2022-11-13 11:52 UTC, mikedld commented
The conversation has started in #4147 and continued in #4151, not seeing any issues with that.

I closed it because I've opened a new PR with a proper fix, not because I want to shut you up.

2022-11-13 11:54 UTC, GaryElshaw commented
Not about me.

2022-11-13 12:00 UTC, mikedld commented
s/you/y'all/

2022-11-13 12:04 UTC, GaryElshaw commented
No, you know that's a crap response. I'm about to turn 52, and i know you're an adult, it's all good, but tell me about it.

2022-11-13 18:30 UTC, Coeur commented
Verified working in https://github.com/transmission/transmission/pull/4156.

2022-11-14 04:03 UTC, ckerr commented
> Also, closing an issue is a brutal way to kill conversation.

> No, you know that's a crap response. I'm about to turn 52, and i know you're an adult, it's all good, but tell me about it.

I think there may be a miscommunication here? @mikedld didn't close any issue; that was in 4151 and remained open. He closed this PR because it was superseded by 4156 and linked to it in this PR before closing it.

FWIW closing a superseded PR seems perfectly reasonable to me! I've done the same thing hundreds of times with no intended shade.