MacOS empty tableview rows fix
transmission/transmission pull request #4333
Opened 2022-12-08 03:59 UTC by sweetppro

fixes UI issues on macOS client when Groups are used:
### Before - group headers (autosize disabled)
<img width="653" alt="old groups" src="https://user-images.githubusercontent.com/7323792/206352379-45ff9e6c-ff47-447a-b55f-09269ed89e79.png">

### This PR - group headers(autosize disabled)
<img width="653" alt="new groups" src="https://user-images.githubusercontent.com/7323792/206352393-e1a75a02-f802-4770-820a-25c9e4ab4b42.png">

### Before (autosize enabled) _[copyright free torrents shown]_
https://user-images.githubusercontent.com/7323792/206352891-66bf1534-2688-43df-b9c5-116aa1c3ebd8.mov

### This PR - (autosize enabled) _[copyright free torrents shown]_
https://user-images.githubusercontent.com/7323792/206353139-ea429f85-69e1-4a8a-b498-7ff9097142f7.mov

2022-12-08 04:07 UTC, GaryElshaw commented
Might fix #3397 too.

2022-12-08 04:42 UTC, sweetppro commented
> Should fix #3397 too.

@GaryElshaw It totally fixes this, i did have a quick scan through the issues, but didn’t see anything relevant, ill update my top comment

2022-12-08 04:50 UTC, ckerr commented
@sweetppro please add a one-line "Notes:" line to the PR summary so the release notes script will know what to say :smile_cat:

2022-12-08 08:33 UTC, Coeur requested changes

2022-12-08 08:33 UTC, Coeur commented on macosx/CMakeLists.txt
> +    GroupTextCell.mm
The new files need to be added to the Xcode project too.

2022-12-08 08:35 UTC, Coeur commented on macosx/GroupTextCell.mm
> +// This file Copyright © 2006-2022 Transmission authors and contributors.
Just `© 2022`

2022-12-08 08:36 UTC, Coeur commented on macosx/GroupTextCell.h
> +// This file Copyright © 2006-2022 Transmission authors and contributors.
Just `© 2022`
```suggestion
// This file Copyright © 2022 Transmission authors and contributors.
```

2022-12-08 08:52 UTC, Coeur commented on macosx/TorrentTableView.mm
> +//we override row highlightling because we are custom drawing the group rows
typo:
highlightling > highlighting

2022-12-08 09:53 UTC, Coeur commented on Transmission.xcodeproj/project.pbxproj
> +	objectVersion = 54;
This would break on older Xcode, and for Transmission 4 we need to keep compatibility. So just undo that change, thanks.

2022-12-08 09:57 UTC, sweetppro commented on macosx/GroupTextCell.mm
> +    titleFrame.origin.y = theRect.origin.y - 1.0 + (theRect.size.height - titleSize.height) / 2.0;
the -1.0 gives a better position

2022-12-08 10:04 UTC, Coeur approved these changes
Thanks.
Code verified and tested.

2022-12-09 01:12 UTC, nevack approved these changes
LGTM, well done!

2022-12-09 19:06 UTC, merged