Fix WebUtilsTest.urlParse and psl_builtin for Xcode
transmission/transmission pull request #4642
Opened 2023-01-23 18:16 UTC by Coeur

<s>While ideally psl_builtin should never be null, this pull request adds a workaround which is compatible with most tracker cases (at least, the hundred of popular trackers that I'm aware of) in case psl_builtin is null.

Of course, lacking the [~10k entries of the Public Suffix List](https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat) can't be solved with just maths or a regex, but the code I wrote will give at least better results than just `www` (which was what the function was most often returning before this improvement).</s>

This PR adds libpsl support when using Xcode.

2023-01-23 19:02 UTC, ckerr requested changes
Yeah it does make sense to do something here, thanks for the PR.

IMO the problem is with the dependencies, so IMO should be fixed at that level, rather than by adding more code here. I'd prefer we just add `TR_ASSERT(psl_builtin() != nullptr);` here instead of adding domain guesser code.

2023-01-23 19:28 UTC, Coeur commented
Well, but then my app would crash on launch, ah ah.

But OK for adding the assertion. Just we *first* need to figure out how to get psl_builtin consistently in every build (cmake and Xcode).

2023-01-23 20:36 UTC, Coeur commented
@ckerr first, a PR to update our libpsl fork: https://github.com/transmission/libpsl/pull/1

2023-01-31 07:32 UTC, Coeur commented
@ckerr fixing the build for Xcode is tricky at the moment. Can you accept my workaround for Transmission 4.0.0, and I'll address libpsl build before Transmission 4.1?

2023-01-31 21:58 UTC, ckerr commented
If this isn't a blocker for 4.0.0 then please change the milestone to `decide-after-4.0.0`

If this _is_ a blocker for 4.0.0... what makes it a blocker?

2023-01-31 23:49 UTC, Coeur commented
The feature is broken and this is the fix for it?
Mike once said he's making the releases based on the Xcode builds, so it's a 4.0 blocker for a release.

2023-02-01 00:25 UTC, ckerr commented
>> If this is a blocker for 4.0.0... what makes it a blocker?

> The feature is broken and this is the fix for it?

So `tr_urlParse()` is returning the wrong sitenames in the Xcode builds?

2023-02-01 04:22 UTC, Coeur commented
> So `tr_urlParse()` is returning the wrong sitenames in the Xcode builds?

Indeed. It was just returning whatever comes before the first dot, so "www.tracker.com" would return "www" only.

2023-02-01 05:50 UTC, ckerr approved these changes

2023-02-01 05:51 UTC, merged

2023-02-02 06:26 UTC, ckerr commented
Notes: Fixed [libpsl](https://github.com/rockdaboot/libpsl) dependency build issue on macOS.