forms fine tuning and "contrast-prefers: more"
transmission/transmission pull request #5465
Opened 2023-04-27 14:24 UTC by klevain

A rescue of this [closed PR](https://github.com/transmission/transmission/pull/5333) and adding support for high contrast theme, [as discussed there](https://github.com/transmission/transmission/pull/5333#issuecomment-1494799930) too.

Here some screenshots :

<img width="256" alt="high-contrast-dark-nav" src="https://user-images.githubusercontent.com/1315866/234891945-9f5b86ac-97af-4f51-a3f5-2505dd9931ad.png"><img width="256" alt="high-contrast-dark" src="https://user-images.githubusercontent.com/1315866/234891969-afa91fdd-e145-4959-85b4-b77580250cc7.png"><img width="256" alt="high-contrast-light" src="https://user-images.githubusercontent.com/1315866/234891976-1e067f4d-421a-4aaf-be88-659faf437ea4.png"><img width="256" alt="low-contrast-dark-nav" src="https://user-images.githubusercontent.com/1315866/234891989-cfcf40ec-09f2-44e4-ba36-58f3ab80e514.png"><img width="256" alt="low-contrast-light" src="https://user-images.githubusercontent.com/1315866/234891997-208cdc7d-f31d-4eb6-b422-549195878586.png">

2023-04-27 17:55 UTC, ckerr requested changes
There's so much going on in this PR. It changes the input dialogs, it adds contrast mode, it's fixing breaking spaces, etc.

Would it be possible to break this into single-topic PRs? There's some of it, e.g. the fixes, that I'd like to include in a 4.0.x release but other enhancements that probably don't make sense for a bugfix release.

Marking as "Request changes" but for the record I like the direction this code is going & hope use all these pieces when all is said & done

2023-04-27 17:55 UTC, ckerr commented on third-party/libdeflate
This PR shouldn't be changing libdeflate

2023-04-27 17:55 UTC, ckerr commented on web/public_html/transmission-app.js
Please don't change transmission-app in your PRs; a bot generates this file automatically

2023-05-02 07:43 UTC, klevain commented
I close this one in favor of [this one](https://github.com/transmission/transmission/pull/5470#event-9130968115).

2023-05-02 07:44 UTC, closed without merging