updating debian release
transmission/transmission pull request #6030
Opened 2023-09-23 11:28 UTC by jemadux

i am  using now debian 12 and with those commands that are on debian working fine .. so I decide it that will good idea to push it

2023-09-23 11:42 UTC, nevack commented
Why not specify both?
`oldstable` releases are pretty common in the wild

2023-09-26 01:40 UTC, ckerr requested changes

2023-09-26 01:40 UTC, ckerr commented on docs/Building-Transmission.md
> +#### Debian 12 / Bookworm ####
I like the idea of including 12, but this does lose the fact that one can build on 11 this way... so how about:

```suggestion
#### Debian 11 and Newer ####
```

2023-09-28 06:27 UTC, ile6695 commented
https://github.com/transmission/transmission/pull/5866 Has been in limbo for a while now. In 12 there is new Qt6 support.

2023-10-01 15:44 UTC, ckerr approved these changes

2023-10-01 15:47 UTC, merged