fix: EVUTIL_SET_SOCKET_ERROR(0) to avoid err EAGAIN with n_read 0
transmission/transmission pull request #6090
Opened 2023-10-08 21:19 UTC by Coeur

Possible fix for #5943.
Address possible regression from #5543 in May 2023.

After the call to recv:
https://github.com/transmission/transmission/blob/0c52b710ad241c2b68cb9c7a9eb68a8532b290d0/libtransmission/tr-buffer.h#L203

The value in `n_read` may be 0 with errno set to EAGAIN (instead of being `n_read` -1). This might steam from the removal of EVUTIL_SET_SOCKET_ERROR(0) in #5543. And when `n_read` is 0, then error is set to ENOTCONN (instead of EAGAIN), and peer is lost.

This is speculation. I'll continue to test this potential fix for the regression that I started to observe in June 2023.

2023-10-08 23:51 UTC, Coeur commented
That didn't work: magnet metadata still stuck at 50% until I restart Transmission.

2023-10-09 03:02 UTC, ckerr requested changes
Good catch. I approve of the idea of what this PR is trying to do.

This isn't going to do what you want on Windows, though where `sockerrno` is a macro for `WSAGetLastError()`.

Probably there needs to be a macro to set sockerrno that would be a simple assignment on mac/linux and call `WSASetLastError()` on Windows.

2023-10-09 03:33 UTC, tearfur commented
Sorry, I'm not catching on to the idea of this PR.

Isn't the value of `auto const err = sockerrno` only used if `nread == -1`? In that case `socketerrno` will be set by the `recv()` call, so what's setting it to `0` before gonna do?

2023-10-12 00:17 UTC, Coeur commented
@tearfur I was experiencing seemingly a situation with `nread == 0` + `socketerrno == EAGAIN` ... and that was throwing ENOTCONN. Setting socketerrno to 0 did prevent that scenario. I'm speculating, but maybe `recv` implementation on Mac will return a -1 value only when socketerrno is modified? So if previous value was EAGAIN and new value is EAGAIN, it would return 0 instead of -1?

2023-10-12 01:55 UTC, tearfur commented
If `recv()` returns `0`, then it just means the TCP connection closed normally with the FIN handshake.

The manpages of `recv()` did not say what will the value of `errno` be when `nread != -1`, so it is perfectly reasonable that the `errno` was left unmodfied (i.e. `EAGAIN` before and after `recv()`), and we don't need to worry about it either.

That's also why I opened #6029 in the first place, so that people won't mistake `ENOTCONN` as something out of the ordinary.

2023-10-13 18:00 UTC, Coeur commented
That may be possible. Closing.

2023-10-13 18:00 UTC, closed without merging