Give each filter its own label
transmission/transmission pull request #6573
Opened 2024-02-04 18:42 UTC by ile6695

Closes #5537

2024-03-23 12:27 UTC, Coeur approved these changes

2024-04-01 15:30 UTC, ckerr reviewed
@ile6695 thanks for the PR! I appreciate both this & earlier code you've submitted to the project, and hope you keep contributing after this PR.

- At the code level, I don't think the `FilterBar::activity_label_` and `FilterBar::tracker_label_` fields are needed? We can just create these widgets as we add them to the layout: `h->addWidget(new QLabel{ tr("Status:"), this });` Marking as "Request changes" for this item.

- At the feature level... I see @tearfur marked 5537 as `pr welcome` so maybe I am wrong, but IMO the dropdowns are already self-explanatory and real estate on that bar is _valuable_. If @tearfur or anyone else feels strongly about adding this change please LMK, but otherwise I'd prefer to not use this real estate on labels.

2024-04-01 15:30 UTC, ckerr requested changes
@ile6695 thanks for the PR! I appreciate both this & earlier code you've submitted to the project, and hope you keep contributing after this PR.

- At the code level, I don't think the `FilterBar::activity_label_` and `FilterBar::tracker_label_` fields are needed? We can just create these widgets as we add them to the layout: `h->addWidget(new QLabel{ tr("Status:"), this });` Marking as "Request changes" for this item.

- At the feature level... I see @tearfur marked 5537 as `pr welcome` so maybe I am wrong, but IMO the dropdowns are already self-explanatory and real estate on that bar is _valuable_. If @tearfur or anyone else feels strongly about adding this change please LMK, but otherwise I'd prefer to not use this real estate on labels.

2024-04-01 19:18 UTC, ile6695 commented
Thank you for feedback @ckerr
I made this pr because I had extra time and saw a simple 1 year old ```pr welcome``` issue. No hard feelings if <10 line pr gets rejected :smile:

- Code level:
I didn't really think about creating labels as they're needed because the old one was made in ```FilterBar::FilterBar``` constructor.

- Feature level:
UI stuff is hard. So many different solutions that all could work. "Status:" could be replaced with "Filters:" to fit better with the two ComboBoxes that come after it.

2024-04-01 20:54 UTC, closed without merging