fix crash on ENOTSOCK
transmission/transmission pull request #6585
Opened 2024-02-07 14:03 UTC by Coeur

fix #6581

2024-02-08 07:36 UTC, tearfur requested changes
Please delete the `TR_ASSERT_MSG` line that caused the abort instead of checking `len == 0` here.

Today I learned that we shouldn't trust inputs even from a famous, widely-used OS. 🐱

2024-02-09 01:05 UTC, tearfur approved these changes

2024-02-09 01:08 UTC, tearfur commented
Please update the PR description as well.

2024-02-11 15:34 UTC, ckerr commented
Does this need to go in 4.0.x as well?

2024-02-11 17:41 UTC, tearfur commented
@ckerr No, this is not an issue in `4.0.x`.

2024-02-11 21:20 UTC, Coeur commented
Notes: fix rare crash on empty filedescriptor

2024-02-12 02:40 UTC, merged