bumping small/libdeflate/utfcpp to newer versions
transmission/transmission pull request #6709
Opened 2024-03-16 05:31 UTC by Coeur

- bumping small from 0.2.0 to 0.2.1
- bumping libdeflate from 1.18 to 1.19
- bumping utfcpp from 3.2.1 to 4.0.5
- using original repositories when there are zero modifications necessary for Transmission, allowing easier updates of those dependencies

2024-03-16 05:42 UTC, tearfur commented
I'm going to wait for Charles to give his opinion first. He has his reasons for using forks after all https://github.com/transmission/transmission/pull/6138#discussion_r1367184713.

2024-03-16 11:03 UTC, Coeur commented
If there is ever an upstream repo breakage, then we would simply update the link to a fork. But it's causing too much hassle to discover and update the third-party versions when they are gated by our unmaintained fork.

2024-03-16 11:07 UTC, Coeur commented
@tearfur there is one for you: the latest small doesn't build with GCC 8.5 on NetBSD/amd64:
https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity/405198?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandchucktcpluginBuild=true&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildChangesSection=true
```
In file included from ../../third-party/small/include/small/map.hpp:11,
                 from ../../libtransmission/announce-list.cc:11:
../../third-party/small/include/small/vector.hpp: In member function 'constexpr small::vector<T, N, Allocator, AllowHeap, SizeType, GrowthFactor>::iterator small::vector<T, N, Allocator, AllowHeap, SizeType, GrowthFactor>::erase(small::vector<T, N, Allocator, AllowHeap, SizeType, GrowthFactor>::const_iterator, small::vector<T, N, Allocator, AllowHeap, SizeType, GrowthFactor>::const_iterator)':
../../third-party/small/include/small/vector.hpp:1090:26: error: 'for_each_n' is not a member of 'std'
                     std::for_each_n(
                          ^~~~~~~~~~
../../third-party/small/include/small/vector.hpp:1090:26: note: suggested alternative: 'for_each'
                     std::for_each_n(
                          ^~~~~~~~~~
                          for_each
Process exited with code 1
```

2024-03-16 12:10 UTC, tearfur commented
That's annoying... Right I'll create a PR at upstream.

2024-03-16 14:24 UTC, nevack commented
> That's annoying... Right I'll create a PR at upstream.

I wanted to say "Do we really need to support such rather old compilers?", but GCC 8.5.0 is not even 3 years old, and for C/C++ compiler it's like yesterday :smile:

2024-03-16 18:11 UTC, ckerr requested changes
For the reasons that @tearfur linked to, I'd prefer to have `transmission/transmission` git dependencies pointing to other `transmission/*` repositories. 

I'm happy to sync any modules.

TBH I don't think this is even a how-many-people-have-permission issue; it would be better if none of us had to do this chore. I'll look to see if there's a way to automate the task.

Other than that, I'm :+1: on the idea of bumping dependencies as long as CI is happy

2024-03-16 18:13 UTC, ckerr commented
> TBH I don't think this is even a how-many-people-have-permission issue; it would be better if none of us had to do this chore. I'll look to see if there's a way to automate the task.

Looks like https://github.com/apps/pull might be good

2024-03-16 18:51 UTC, tearfur commented
> I'll look to see if there's a way to automate the task.

Oh yes please!

2024-03-17 03:35 UTC, Coeur commented
Note that I do not have the privilege to dismiss a review:
![Capture d’écran 2024-03-17 à 11 34 03](https://github.com/transmission/transmission/assets/839992/ec6afd20-5004-43ab-bec2-c7e4e05f0a0d)

2024-03-17 04:54 UTC, Coeur commented
Ah, the fix for small has landed: https://github.com/alandefreitas/small/pull/44.
Let me re-add `small` update.

2024-03-17 14:43 UTC, Coeur commented
> I'm happy to sync any modules.

You'll need to re-sync `small` for this PR, @ckerr.

2024-03-17 14:55 UTC, tearfur commented
> Looks like https://github.com/apps/pull might be good

@ckerr Looks promising to me too.

2024-03-17 20:10 UTC, ckerr commented
I've installed https://github.com/apps/pull for https://github.com/transmission/fmt as a trial installation. Since upstream fmt gets commits pretty frequently, we can watch our fork and see how it works out.

Doesn't look like there are any configuration options for `apps/pull` e.g. on how often to check, so my _guess_ is it'll be triggered whenever there are upstream commits  :man_shrugging: we'll see

2024-03-17 20:45 UTC, ckerr approved these changes

2024-03-17 22:28 UTC, merged

2024-03-18 05:56 UTC, tearfur commented
@Coeur Can you link #6709 to this issue? If I remember correctly, GitHub will automatically close it once you do.