clarify DhtPort specific usage
transmission/transmission pull request #6963
Opened 2024-06-30 22:37 UTC by reardonia

confused myself until I realized this was DHT-specific.  Make it clear in code.

2024-07-01 05:11 UTC, tearfur requested changes

2024-07-01 05:11 UTC, tearfur commented on libtransmission/peer-msgs.cc
>      size_t protocol_send_port(tr_port const port) const
```suggestion
    size_t protocol_send_dht_port(tr_port const port) const
```

2024-07-02 04:06 UTC, tearfur approved these changes

2024-07-11 00:07 UTC, mikedld approved these changes

2024-07-11 00:42 UTC, merged