handshake: add fire_timer() explicitly instead of overloading fire_done()
transmission/transmission pull request #6966
Opened 2024-07-01 21:06 UTC by reardonia

Add explicit funtion for timer expiration so that we can log it separately, and then pass through to fire_done().

Currently, tr_handshake sets up a timer and directs it to the fire_done() exit path, so fire_done() doesn't know if it was called due to a timer expiring.

"Draft" because I then realized that timer expiritation does not currently clear_callbacks() though it feels like it should. Every other exit path goes through done()  and thus does clear_callbacks().  Thoughts?

2024-07-10 02:29 UTC, tearfur commented
> "Draft" because I realized that timer expiritation does not currently clear_callbacks() though it feels like it should. Every other exit path goes through done() and thus does clear_callbacks(). Thoughts?

It probably doesn't matter, because the timer cannot fire in an unsafe way anyway. But I agree that it should be called within `fire_done()` just to be safe.

2024-07-10 02:30 UTC, tearfur requested changes

2024-07-10 02:30 UTC, tearfur commented on libtransmission/handshake.cc
> +    return (fire_done(is_connected));
```suggestion
void tr_handshake::fire_timer()
{
    tr_logAddTraceHand(this, "timer expired");
    fire_done(false);
```

2024-07-11 01:34 UTC, tearfur approved these changes

2024-12-13 23:33 UTC, reardonia commented
@ckerr checking if you are considering a few of my PR for 4.1

2024-12-14 21:14 UTC, ckerr approved these changes

2024-12-14 21:14 UTC, merged