build: enable clang-tidy by default (#4821)
transmission/transmission pull request #6989
Opened 2024-07-12 09:10 UTC by rsekman

In #4824 running clang-tidy was disabled by default due to an upstream bug that led to an infinite loop. See #4821 This bug has since been fixed in clang-tidy 18. It is therefore safe to re-enable clang-tidy by default. I have checked that the build completes on clang 18, version information below.

```
% uname -a
Linux naoetsu 6.9.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000 x86_64 GNU/Linux
% clang -v
clang version 18.1.8
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/13.3.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/14.1.1
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.3.0
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Found CUDA installation: /opt/cuda, version 
% clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 18.1.8
  Optimized build.
```

2024-07-12 16:02 UTC, tearfur requested changes

2024-07-12 16:02 UTC, tearfur commented on CMakeLists.txt
> +tr_auto_option(RUN_CLANG_TIDY "Run clang-tidy on the code" ON)
```suggestion
tr_auto_option(RUN_CLANG_TIDY "Run clang-tidy on the code" AUTO)
```

2024-07-15 01:42 UTC, tearfur approved these changes

2024-08-13 00:21 UTC, mikedld approved these changes

2024-08-13 00:48 UTC, mikedld commented
Android build seems to find/use clang-tidy now, based purely on increased build times and it timing out. Let's try disabling it since we're not interested in it (?), probably somewhere here: https://github.com/transmission/transmission/blob/35ef8cf7a060bd5631ee0568ebd8a264480c650a/android/build.gradle#L35

2024-08-24 17:23 UTC, ckerr approved these changes

2024-08-24 17:27 UTC, ckerr requested changes
Seems to still be used on Android by default?

GitHub Actions has been going on the Android build for over four hours now. We can't merge something that causes CI to run for four hours for every change :skull:

2024-08-25 23:11 UTC, mikedld commented
Seems like disabling clang-tidy for the Android CI build helped. I'm going to assume this satisfies both me and @ckerr and merge this.

2024-08-25 23:11 UTC, merged