fix: silence bugprone-unchecked-optional-access warnings
transmission/transmission pull request #6990
Opened 2024-07-12 09:21 UTC by rsekman

clang-tidy emits bugprone-unchecked-optional-access warning for `tr_sys_file_lock`. however, this is a false positive: the lines warned about cannot be reached if the optional does not contain a value. adding an `assert` silences these warnings.

2024-07-12 18:10 UTC, tearfur requested changes

2024-07-12 18:10 UTC, tearfur commented on libtransmission/file-posix.cc
> +    assert(result);
```suggestion
    TR_ASSERT(result);
```

2024-07-12 18:10 UTC, tearfur commented on libtransmission/file-posix.cc
> +#include <cassert>
```suggestion
```

2024-07-14 12:34 UTC, tearfur approved these changes

2024-08-13 00:50 UTC, mikedld approved these changes

2024-08-13 00:51 UTC, merged