fix: make name and hash readable
transmission/transmission pull request #7014
Opened 2024-07-26 18:59 UTC by Rukario

Supersedes: #6288 along with more fixes

Left: This PR, Right: Original
![Transmission no-escaping](https://github.com/user-attachments/assets/37e89bd8-9ccb-4d70-b6da-494d4e922bf4)

The top part of the screenshot is observation of a problem that calls for an addition of name to the info page.

Notes: Fixed truncated hash in inspector page, added name section to inspector page

2024-07-26 22:32 UTC, killemov requested changes
Maybe make a switch on torrent.length? (0,1, default?)

2024-07-27 07:31 UTC, killemov approved these changes

2024-08-01 03:40 UTC, tearfur approved these changes

2024-08-22 23:04 UTC, ckerr approved these changes

2024-08-22 23:04 UTC, merged

2024-08-23 23:52 UTC, Rukario commented
Well, look who's back :D