feat: sequential download in `torrent-add` and `sesssion-*` RPC methods
transmission/transmission pull request #7047
Opened 2024-08-07 08:35 UTC by tearfur

Fixes #7004.

Notes: Added optional sequential downloading.

2024-08-07 09:06 UTC, tearfur commented
Just a heads up, I also want to convert the quark `sequentialDownload` to snake_case after the pending RPC and transmission-remote PRs are merged.

Right now, I'm holding back on it to avoid merge conflicts.

2024-08-08 09:56 UTC, killemov requested changes
In https://github.com/transmission/transmission/pull/7047/files#diff-393f1a3078d6a5f14bc7c34b1424e4fee3badbfe5fda1f181c416f5850f87666
actual_keys => actualKeys?
ExpectedKeys => expectedKeys?
missing_keys => missingKeys?
unexpected_keys => unexpectedKeys?

2024-08-08 11:45 UTC, tearfur commented
> actual_keys => actualKeys?
> ExpectedKeys => expectedKeys?
> missing_keys => missingKeys?
> unexpected_keys => unexpectedKeys?

The current state is following the coding style enforced by clang-tidy, so I will not touch them.

https://github.com/transmission/transmission/blob/3e9f5f614a875aae987235d3836d0ca555a80d80/tests/libtransmission/.clang-tidy#L40

https://github.com/transmission/transmission/blob/3e9f5f614a875aae987235d3836d0ca555a80d80/tests/libtransmission/.clang-tidy#L51

2024-12-15 01:02 UTC, Pentaphon commented
@ckerr can we have this to make sequential downloading complete in the 4.1.0 betas?

2024-12-16 13:36 UTC, killemov approved these changes
These changes seem straightforward enough. On to the clients!

2025-03-10 02:15 UTC, tearfur commented
@ckerr ping

2025-03-10 17:07 UTC, merged

2025-04-14 11:43 UTC, emanuele-albini commented
Thanks for adding this feature to Transmission. I'm trying to use it in the MacOS client 4.1.0-beta.2 but I cannot find the boolean flag in the configuration file `$HOME/Library/Preferences/org.m0k.transmission.plist` (see [Configuration Location](https://github.com/transmission/transmission/blob/main/docs/Configuration-Files.md). Where should the flag be enabled?

2025-04-14 19:29 UTC, nevack commented
> Thanks for adding this feature to Transmission. I'm trying to use it in the MacOS client 4.1.0-beta.2 but I cannot find the boolean flag in the configuration file `$HOME/Library/Preferences/org.m0k.transmission.plist` (see [Configuration Location](https://github.com/transmission/transmission/blob/main/docs/Configuration-Files.md?rgh-link-date=2025-04-14T11%3A43%3A11Z). Where should the flag be enabled?

AFAIK, this option is not yet supported in macOS client.

2025-04-29 03:18 UTC, tearfur commented
Technically it's still possible to enable it via the RPC interface on the macOS client, but IIUC the setting won't persists across session like it would on other clients.

It's a pain-in-the-ass because the macOS client uses a different mechanism from other clients to store configurations, so any new configurations have to be ported over.