ci: remove macos-12-x86_64-from-tarball from GitHub workflows
transmission/transmission pull request #7166
Opened 2024-10-13 18:52 UTC by ckerr

Remove `macos-12-x86_64-from-tarball` CI action.

> Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!
>
> Error: You are using macOS 12.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

Example: https://github.com/transmission/transmission/actions/runs/11316014753/job/31467946321

2024-10-13 23:34 UTC, nevack commented
@ckerr There's also `macos-12` workflow, checking sources without tarball.
Better migrate both to `macos-13`, without removing

2024-10-14 12:59 UTC, nevack approved these changes
LGTM, thanks Charles!

2024-10-14 17:57 UTC, ckerr commented on .github/workflows/actions.yml
> -      - name: Set Xcode to 13.2.1
@nevack is there a reason to prefer either 14 or 15? The default is 15.2

2024-10-14 19:05 UTC, nevack commented on .github/workflows/actions.yml
> -      - name: Set Xcode to 13.2.1
I think the main reason here is to test for FTBFS for the lowest supported macOS SDK within GHA runners.
No other reasons in my mind.

2024-10-15 01:03 UTC, Coeur commented on .github/workflows/actions.yml
> -      - name: Set Xcode to 13.2.1
@ckerr please keep this target on the oldest supported Xcode. For macOS 13, it would be Xcode 14.3.1 as stated by nevack.

2024-10-15 01:09 UTC, Coeur requested changes
I think that the issues with brew are only warnings.
The actual error in the build is:
```
ERROR: /private/tmp/qt-20241013-11151-tksgsd/qt-everywhere-src-6.7.2/qtbase/src/gui/bus_interface.h:22 includes private header QtGui/private/qspi_struct_marshallers_p.h
```
aka, something to do with QT?

2024-10-15 01:20 UTC, nevack commented
> I think that the issues with brew are only warnings.

You are not wrong.
Homebrew just stopped providing bottles (aka prebuild packages) for macOS 12, and now every package we install via brew is being built from source.
Another outcome of this is brew does not guarantee their packages are buildable on/for this OS version.

So we need to move on anyway.

2024-10-15 01:27 UTC, Coeur commented
I've made my own fix attempt for this issue: #7169
This will keep testing the mac build on macos-12. I only moved the QT build to macos-13.

2024-10-21 09:51 UTC, closed without merging