feat: disconnect blocklisted peers on blocklist update
transmission/transmission pull request #7167
Opened 2024-10-14 16:15 UTC by cdowen

Mark peer to be disconnected upon blocklist update. Tested on my torrent, seems to be working.

I am not familiar with transmission code or cpp. Hope the fix does not cause any problems.

Notes: Disconnect blocklisted peers immediately upon blocklist update.

Fix #732 .

2024-10-14 21:10 UTC, reardonia commented on libtransmission/peer-mgr.cc
> +                }
perhaps also worth a logdebug or even logwarn

2024-10-15 03:54 UTC, reardonia approved these changes

2024-10-18 06:17 UTC, tearfur requested changes

2024-10-18 06:17 UTC, tearfur commented on libtransmission/peer-mgr.cc
> +                    tr_logAddDebug(fmt::format("Peer {} blocked in blocklists update", peer->display_name()));
```suggestion
                    tr_logAddDebugTor(tor, fmt::format("Peer {} blocked in blocklists update", peer->display_name()));
```

2024-10-18 07:43 UTC, tearfur approved these changes

2024-11-04 05:28 UTC, Anuskuss commented
How would Transmission even know that either `blocklist-url` or it's content changed? Don't you have to restart it either way?

2025-03-09 15:24 UTC, tearfur commented
@ckerr ping

2025-03-09 22:38 UTC, ckerr approved these changes

2025-03-09 23:33 UTC, merged