feat: add peer traffic statistics to rpc call
transmission/transmission pull request #7172
Opened 2024-10-15 20:21 UTC by cdowen

This is intended for external tools such as [PeerBanHelper](https://github.com/PBH-BTN/PeerBanHelper) to perform anti-leeching based on peer traffic statistics. Anti-leeching is really important to some Transmission users like me.

Two new keys, `bytesToClient` and `bytesToPeer` are added in the `peers` field returned by the `torrent-get` method, which represent download and upload traffic from a specific peer. Traffic data is computed from num of blocks. This is not very accurate as block size may vary in the last block, but should be enough for anti-leeching purpose.

I test the change on my torrents. But currently I cannot verify if the traffic data is correct.

Should help partly fix `#6978`, as Transmission can provide enough info for external tools to perform anti-leeching now.

Notes: Add peer traffic statistics to `torrent-get` rpc method.

2024-12-27 03:42 UTC, tearfur requested changes
I'd say add `bytes_sent_to_peer` and `bytes_sent_to_client` to `tr_peer` for an accurate number.

If these new fields are added, people ***will*** start using it for purposes other than anti-leeching, and they might need it to be accurate.

2025-04-01 09:19 UTC, tearfur commented on libtransmission/peer-mgr.h
> +    size_t bytes_sent_to_peer_ = 0;
These 2 fields are different from `tr_peer.blocks_sent_to_client` and `tr_peer.cancels_sent_to_peer` in that they are:

1. Persistent across connect/discconects.
2. Cumulative across the entire Transmission session (as opposed to be cumulative over the last `n` seconds)

Can you help me understand why are they the way they are? If there's a good reason, then `bytesToClient` and `bytesToPeer` needs a different name to differentiate from `blocksToPeer` and `bytesToPeer`.

https://github.com/transmission/transmission/blob/ac5c9e082da257e102eb4ff18f2e433976a585d1/libtransmission/peer-common.h#L262-L266

2025-04-04 19:58 UTC, Ghost-chu commented on libtransmission/peer-mgr.h
> +    size_t bytes_sent_to_peer_ = 0;
I tend to keep the same behavior as libtorrent, but it's fine even if it's not persistent. An external tool should be able to handle this.

2025-04-05 14:07 UTC, tearfur commented on libtransmission/peer-mgr.h
> +    size_t bytes_sent_to_peer_ = 0;
If it works for 3rd party tools, then I prefer to keep `bytesToClient` and `bytesToPeer` consistent with `blocksToPeer` and `blocksToClient`, so that it's less confusing for RPC API users. That means:

1. The stats reset as soon as the peer disconnects.
2. Cumulative over the last 60 seconds.

It should be pretty straightforward to implement, the code is 90% similar. Thanks for your work @cdowen!

2025-04-05 14:09 UTC, tearfur requested changes

2025-04-05 14:09 UTC, tearfur commented on docs/rpc-spec.md
> +| `bytesToPeer`        | number     | tr_peer_stat
Please change the case style to snake_case. All new API should use snake_case from `4.1.0`. (See #2855)

2025-04-06 10:43 UTC, tearfur commented on libtransmission/peer-mgr.cc
> +                msgs->bytes_sent_to_peer.add(tr_time(), event.length);
*nit*: This line should be in `tr_peerMsgsImpl::did_write()`, since it only concerns the peer.

2025-04-07 00:51 UTC, tearfur approved these changes

2025-11-03 03:48 UTC, tearfur commented
@ckerr ping

2025-11-10 15:41 UTC, merged