build: refuse to build with libcurl 8.9.1
transmission/transmission pull request #7304
Opened 2024-12-15 23:07 UTC by ckerr

Fixes #7035.

2024-12-16 15:30 UTC, tearfur approved these changes

2024-12-16 15:30 UTC, tearfur commented on CMakeLists.txt
> +if("${CURL_VERSION}" VERSION_EQUAL "8.9.1")
Just pointing out that this would suffice.

```suggestion
if(CURL_VERSION VERSION_EQUAL "8.9.1")
```

2024-12-25 17:00 UTC, ile6695 approved these changes

2024-12-25 22:56 UTC, ile6695 approved these changes

2025-02-27 09:02 UTC, tearfur requested changes
I previously approved this PR, but now I suggest to merge #7457 instead.

People can still dynamically link curl 8.9.1 to Transmission after this PR, so I think a warning in log should be more helpful than stopping the build.

2025-03-03 07:55 UTC, Coeur commented
We could do both, the build prevention and the log.
Anyway, more than 2 months to address a build issue is way too long to wait.

Now you also need to prevent building with curl 8.11.1 (https://curl.se/docs/CVE-2025-0665.html).

2025-03-04 05:44 UTC, ckerr commented
I think this is mooted by #7447, is that correct? If so, let's close this one

2025-03-04 05:46 UTC, ckerr commented
> Now you also need to prevent building with curl 8.11.1 (https://curl.se/docs/CVE-2025-0665.html).

Probably belongs in its own PR :sob:

2025-03-04 05:56 UTC, tearfur commented
> I think this is mooted by #7447, is that correct? If so, let's close this one

#7447 addresses a whole other problem, but I still agree to close this one because #7457 is merged. I don't think we need to prevent people from building.

2025-03-04 14:44 UTC, closed without merging