free the info resource if failed
transmission/transmission pull request #80
Opened 2016-11-07 06:08 UTC by seiyap70

free the info resource if failed

2016-11-07 17:02 UTC, mikedld requested changes

2016-11-07 17:02 UTC, mikedld commented on libtransmission/torrent-magnet.c
> +                      tr_metainfoFree(&info);
If `tr_metainfoParse` returns `false`, the info has already been freed by `tr_metainfoParse` itself (see  its quite concise implementation); calling `tr_metainfoFree` again here will not lead to trouble (luckily, due to `tr_metainfoFree` zeroing the memory so all the pointers are NULL) but still looks odd and may even be prone to errors on future refactoring. We only need to call `tr_metainfoFree` if `tr_metainfoParse` returned `true`, so this call needs to be moved higher, into the `if (success && !tr_getBlockSize (info.pieceSize))` block.

2016-11-07 22:23 UTC, cfpp2p commented
Also see `torrent.c` `torrentParseImpl()` where following the call to `tr_metainfoParse()`,  `tr_getBlockSize()` can result with TR_PARSE_ERR but `tr_metainfoFree()` not being called here either.

2016-12-09 19:02 UTC, merged

2016-12-09 19:04 UTC, mikedld commented
Merged with a small change per my review comment. Thanks!